#!/usr/bin/env bash

set -e

pip install uv

uv venv --python=3.13 homeassistant

source homeassistant/bin/activate

uv pip install -r requirements.test.txt

hass --config config --script ensure_config

if ! grep -R "logger" config/configuration.yaml >> /dev/null;then
echo "
logger:
  default: error
  logs:
    custom_components.wallpanel_media_player: debug

media_player:
  - platform: wallpanel_media_player
    name: Wallpanel Media Player
    address: http://127.0.0.1:2971" >> config/configuration.yaml
fi
